spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpablog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: bigff

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true


logging:
  level:
    root: info
    com.bigff.blog: debug
  file:
    name: log/blog-dev.log
server:
  port: 8888

